# GREEN-PI DOCKER CONTAINER
---
version: '3'

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - web
    links:
      - db
    volumes:
      - grafana_data:/var/lib/grafana
  green-pi:
    build: .
    networks:
      - web
    links:
      - db
    environment:
      GREEN_PI_DB_CONNECTION: postgresql://green-pi:green-pi@db:5432/green-pi-db
    command: python ./green-pi.py
  green-pi-api:
    build: .
    command: gunicorn api:app -b 0.0.0.0 --access-logfile=/dev/stdout --error-logfile=/dev/stdout
    networks:
      - web
    links:
      - db
    environment:
      GREEN_PI_DB_CONNECTION: postgresql://green-pi:green-pi@db:5432/green-pi-db
    ports:
      - 8000:8000
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: "green-pi"
      POSTGRES_USER: "green-pi"
      POSTGRES_DB: "green-pi-db"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
    networks:
      - web
    ports:
      - 5432:5432

networks:
  web:
    driver: bridge
volumes:
  grafana_data:
    driver: local
  db_data:
    driver: local
