#################################################
# Set-up Raspberry Pi
#################################################
---
- hosts: new-pi
  become: true
  remote_user: pi
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files: vars/default.yml
  tasks:

            # Build container
    - name: Build Docker Container
      docker_image:
        name: green-pi
        path: /home/pi/green-pi/

    # Start container
    - name: Start Green Pi container
      docker_container:
        name: green-pi
        image: green-pi:latest
        state: started